name: Deploy Website and Lambda
on:
  push:
    branches: [ main ]

jobs:
  deploy-website:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      
      - name: Sync to S3
        run: aws s3 sync --delete ./prod s3://gregorychisholm.com

      - name: Invalidate CloudFront Cache
        run: aws cloudfront create-invalidation --distribution-id ${{ secrets.DISTRIBUTION_ID }} --paths "/*"

  deploy-lambda:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2  # Needed to check for file changes

      - name: Check for Lambda changes
        id: lambda-changes
        run: |
          if git diff --name-only HEAD~1 HEAD | grep -q "^lambda/"; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Configure AWS Credentials
        if: steps.lambda-changes.outputs.changed == 'true'
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Zip Lambda code
        if: steps.lambda-changes.outputs.changed == 'true'
        run: |
          cd lambda
          zip -r function.zip . -x "*.git*"

      - name: Update Lambda Function
        if: steps.lambda-changes.outputs.changed == 'true'
        run: aws lambda update-function-code --function-name VisitorCountFunc --zip-file fileb://lambda/function.zip
